### ISSUE TITLE
Quickfix Checklist

### ISSUE THREAD

**Issue by JakeCataford** [Shopify/unity-buy-sdk-examples#30]
- [ ] Move md files under "assets"
- [ ] Maybe import a markdown viewer editor script or something?
- [ ] Include Menu items under help to link to the markdown files directly in the repo for easy reading
- [ ] Find alternative font for UI
- [ ] Ensure default/demo shop has serialized access token embedded in demo scene
- [ ] Clear up trashy rendering of UI on screen, has some blurry edges
- [ ] Maybe take another stab at animating the UI?
- [ ] Maybe make the intro a bit more involved?
- [ ] Stop canvas from re-laying itself out on show/hide (small performance dip)
- [ ] Maybe Give the camera an idle animation
- [ ] Don't import animations on all model imports
- [x] Remove tree thing
- [ ] Delete useless files
- [ ] Use forward rendering path
- [ ] Figure out what to do about event system
- [ ] Finish filling out documentation

Smoke test before pushing to Unity-SDK repo:

- [ ] Test out with some unity developers to make sure the import process/usability is smooth
- [ ] Ensure it builds to standalone/mobile
- [ ] Ensure prefab works in a new scene
- [ ] Make sure latest lighting is baked in

**Comment by JakeCataford** [comment]
ping @mikkoh @coreypollock 

I've prioritized these somewhat from top-down... feel free to edit and add new things if you notice anything

**Comment by coreypollock** [comment]
Looks good 👍🏼 Biggest priorities should be tasks that make the setup and understanding of the SDK and this example experience straightforward and easy.
